name: Azure VM Deploy

on:
  push:
    branches: [ "main", "feature/ci-cd-setup" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 애저 서버 원격 접속 및 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        password: ${{ secrets.AZURE_PASSWORD }}
        port: 22
        script: |
          # 1. 방금 찾아낸 정확한 절대 경로로 이동!
          cd /home/reviewadmin/review-ai-db
          
          # 2. 깃허브에서 최신 코드 당겨오기
          git pull origin main
          
          # 3. 💡 깃허브 금고(Secrets)에서 꺼내어 애저 서버 전용 .env 파일 조립!
          echo "DB_PORT=${{ secrets.DB_PORT }}" > .env
          echo "DB_HOST_PORT=${{ secrets.DB_HOST_PORT }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          
          # 4. 도커 컴포즈로 서버 백그라운드 재시작 (.env를 빨아들여서 실행됨!)
          sudo docker-compose up -d --build